version: "3.9"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - HOST_URL=http://localhost
      - HOST_PORT=8000
      - DATABASE_URL=sqlite+aiosqlite:///./../database.db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
