version: "3.8"

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./../database.db

  frontend:
      build:
        context: client
        dockerfile: Dockerfile
      stdin_open: true
      volumes:
        - ./client:/usr/src/app
      ports:
      - 3000:3000
      environment:
        - NODE_ENV=development